In [2]:
import numpy as np
np.version

<module 'numpy.version' from 'C:\Users\HP\Anaconda2\lib\site-packages\numpy\version.pyc'>

In [3]:
null_arr=np.zeros(10)
null_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
null_arr.nbytes

80

In [5]:
null_arr[5]=1
null_arr

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [6]:
a=np.arange(10,49)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [7]:
a[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [8]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
index=np.array([1,2,0,0,4,0])
index

array([1, 2, 0, 0, 4, 0])

In [10]:
for i in range(len(index)):
    if index[i]==0:
        print("Element is Zero")
    else:
        print("Index of non zero element is "+str(i))

Index of non zero element is 0
Index of non zero element is 1
Element is Zero
Element is Zero
Index of non zero element is 4
Element is Zero


In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
a=np.random.randint(10)
a

7

In [13]:
x3 = np.random.rand(1,10)*10
x3= x3 - x3%1
x3

array([[3., 8., 9., 8., 7., 0., 2., 0., 5., 6.]])

In [14]:
a=np.random.randint(1,10,size=(3,3,3))
a

array([[[5, 1, 7],
        [9, 1, 9],
        [8, 1, 4]],

       [[2, 3, 5],
        [1, 9, 2],
        [1, 5, 4]],

       [[9, 4, 8],
        [4, 8, 9],
        [3, 6, 4]]])

In [15]:
ten_ten=np.random.randint(1,100,size=(10,10))
ten_ten

array([[38, 40, 12, 48, 40, 79, 76, 73, 65, 59],
       [16, 12, 97, 78, 78,  4, 32, 52, 16, 75],
       [26, 34, 50, 96, 26, 74, 41, 37, 92, 88],
       [80, 83, 29, 51, 85, 19, 66,  6, 61, 64],
       [ 7, 96, 62, 67, 92, 19, 21, 93, 81, 87],
       [53, 43, 39, 38, 45, 10, 12, 26,  7, 28],
       [57, 95, 27, 82, 33, 30, 49, 51, 82, 16],
       [46, 20, 50, 50, 11, 83, 64, 67, 33, 64],
       [94, 86,  4, 64, 12, 73, 19, 92, 24, 61],
       [31, 18, 89, 34, 99, 90,  9, 92, 37, 69]])

In [16]:
ten_ten.max()

99

In [17]:
ten_ten.min()

4

In [18]:
ten_ten.argmax()

94

In [19]:
checkerboard=np.zeros(64).reshape(8,8)
checkerboard
checkerboard[1::2,1::2]=1
checkerboard[0::2,0::2]=1
checkerboard

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [55]:
arr3=np.arange(336).reshape(6,7,8)
arr3

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55]],

       [[ 56,  57,  58,  59,  60,  61,  62,  63],
        [ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111]],

       [[112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127],
        [128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 15

In [56]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

In [57]:
a=np.zeros(64).reshape(8,8)
a

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [58]:
np.tile(a,2)
a[1::2,1::2]=1
a[::2,::2]=1
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [75]:
np.diag([1,2,3,4],-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [60]:
a=np.arange(25).reshape(5,5)

In [143]:
a=np.arange(15).reshape(5,3)
b=np.arange(6).reshape(3,2)
c=np.dot(a,b)
c

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [144]:
arr=np.arange(20).reshape(5,4)
b=arr.mean()
b

9.5

In [145]:
x=arr-b

In [146]:
y=arr.std()

In [163]:
a=np.random.randint(0,10,10)
a       

array([4, 3, 5, 0, 9, 0, 5, 7, 6, 1])

In [165]:
a[(a>3) & (a<8)]*=-1
a
#for i in a:
    #if a[i]>3and a[i]<8:
        #a[i]=-a[i]

#print a

array([-4,  3, -5,  0,  9,  0, -5, -7, -6,  1])

In [217]:
arr=np.random.randn(1,10)
arr

array([[ 0.33529491,  1.55447542,  0.7318916 , -0.30422386, -1.64278366,
        -0.73739887,  0.4670232 ,  0.08119005, -0.47135746,  1.08920984]])

In [229]:
b=np.array(5)
b

array(5)

In [230]:
np.copysign(arr,b)

array([[0.33529491, 1.55447542, 0.7318916 , 0.30422386, 1.64278366,
        0.73739887, 0.4670232 , 0.08119005, 0.47135746, 1.08920984]])

In [239]:
np.ceil(arr)

array([[ 1.,  2.,  1., -0., -1., -0.,  1.,  1., -0.,  2.]])

In [240]:
b

array([9, 6, 0, 4, 0, 4, 2, 8, 8, 1])

In [241]:
a=np.random.randint(0,10,10)
b=np.random.randint(0,10,10)
a

array([5, 4, 5, 6, 7, 9, 4, 6, 5, 8])

In [242]:
b

array([1, 5, 2, 8, 3, 1, 2, 6, 5, 6])

In [243]:
np.intersect1d(a,b)

array([5, 6, 8])