In [94]:
import numpy as np
import datetime as dt

In [95]:
a=np.random.rand(1,5)
a

array([[0.6314947 , 0.25318966, 0.73019237, 0.29688337, 0.19476539]])

In [96]:
b=np.random.rand(1,5)
b

array([[0.97588298, 0.97424011, 0.10024279, 0.88082473, 0.62836293]])

In [97]:
s=dt.datetime.now()
c=np.dot(a[0],b[0])
f=dt.datetime.now()
c

1.3200145437160111

In [98]:
s-f

datetime.timedelta(0)

In [99]:
def dotProduct(a,b):
    product=0
  
    for i in range(0,len(a)):
        product=product +a[i] * b[i] 
        
    return product 

s=dt.datetime.now()  
dotProduct(a,b)
f=dt.datetime.now()


In [100]:
s-f

datetime.timedelta(0)

In [93]:
a[0]

array([0.06427242, 0.57303262, 0.59926861, 0.86105991, 0.94598811])